RNMT-3266 Revert support library version to the upstream value
OutSystems/OneSignal-Android-SDK pull request #10
Opened 2019-10-03 17:48 UTC by Chuckytuh

This PR partially reverts changes affecting support library version so that they come directly from upstream as they will be overridden at the plugin level in the context of the [RNMT-3266](https://outsystemsrd.atlassian.net/browse/RNMT-3266)

2019-10-03 17:58 UTC, usernuno approved these changes

2019-10-03 18:10 UTC, cmfsotelo commented
Just adding the _partially_ reverted commit reference here:
https://github.com/OutSystems/OneSignal-Android-SDK/commit/773fdfbf6bc091735aa00bc5e7a47a39f4975894

2019-10-03 18:11 UTC, cmfsotelo approved these changes

2019-10-07 14:06 UTC, cmfsotelo requested changes
As we discussed offline, this pull request was being applied onto a revision that was loosing history due to an orphan merge commit.
I think this PR is no longer needed, because it is being tackled in the pull request:
https://github.com/OutSystems/OneSignal-Android-SDK/pull/11

2019-10-08 17:21 UTC, closed without merging