RNMT-1796 Fix issue of OneSignal deeplink on Androids < 6
OutSystems/OneSignal-Android-SDK pull request #3
Opened 2018-06-21 16:37 UTC by vmfo22

2018-06-21 22:52 UTC, bgracio requested changes

2018-06-21 22:52 UTC, bgracio commented on OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java
> +                if (!url.contains("://"))
Please revert these changes :)

2018-06-22 10:02 UTC, luissilvaos approved these changes

2018-06-22 10:04 UTC, EiyuuZack approved these changes

2018-06-22 10:17 UTC, bgracio approved these changes

2018-06-22 10:20 UTC, merged